Raduga/urls.py
"""
Definition of urls for Raduga.
"""

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from datetime import datetime
import app.forms
import app.views
from django.shortcuts import render, redirect
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('', app.views.home, name='home'),
    path('contact/', app.views.contact, name='contact'),
    path('about/', app.views.about, name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', app.views.registration, name='registration'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('product/', include('product.urls', namespace='product')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.urls import path  
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
  
app_name = 'blog'  
  
urlpatterns = [  
    path('', views.blog, name='blog'),
    path('<id>/', views.blogpost, name='blogpost'),
    path('newpost', views.newpost, name='newpost'),
]

blog/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

#модель данных блога
class Blog(models.Model):
    title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "Автор")
    description = models.TextField(verbose_name = "Краткое содержание")
    content = models.TextField(verbose_name = "Полное содержание")
    posted = models.DateTimeField(default = timezone.now, db_index = True, verbose_name = "Опубликована")
    image = models.FileField(default = 'temp.jpg', verbose_name = "Путь к картинке")
    def get_absolute_url(self): # метод возвращает строку с URL-адресом записи
        return reverse('blog:blogpost', args=[self.id])

    def __str__(self): # метод возвращает название, используемое для представления отдельных записей в административном разделе
        return self.title
    class Meta:
        db_table = "Posts" # имя таблицы для модели
        ordering = ["-posted"] # порядок сортировки данных в модели ("-" означает по убыванию)
        verbose_name = "статья блога" # имя, под которым модель будет отображаться в административном разделе (для одной статьи блога)
        verbose_name_plural = "статьи блога" # тоже для всех статей блога
       
 
admin.site.register(Blog)

#модель комментариев
class Comment(models.Model):
    text = models.TextField(verbose_name = "Комментарий")
    date = models.DateTimeField(default = timezone.now, db_index = True, verbose_name = "Дата")
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "Автор")
    post = models.ForeignKey(Blog, on_delete = models.CASCADE, verbose_name = "Статья")
    
    def __str__(self): # метод возвращает название, используемое для представления отдельных записей в административном разделе
        return 'Комментарий %s к %s' % (self.author, self.post)
    
    class Meta:
        db_table = "Comments" # имя таблицы для модели
        verbose_name = "Комментарий" # имя, под которым модель будет отображаться в административном разделе (для одной статьи блога)
        verbose_name_plural = "Комментарии к статьям блога" # тоже для всех статей блога
        ordering = ["-date"] # порядок сортировки данных в модели ("-" означает по убыванию)

admin.site.register(Comment)

blog/forms.py
from django import forms
from .models import Comment
from django.db import models
from .models import Blog

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text
        
class BlogForm (forms.ModelForm):
    image = forms.FileField(label="Изображение")
    title = forms.CharField(label="Заголовок новости", widget=forms.TextInput(attrs={'class':'form-control require', 'placeholder':'Заголовок'}))
    description = forms.CharField(label="Краткое описание", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Краткое описание'}))
    content = forms.CharField(label="Полное содержание", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Полное содержание'}))
    class Meta:
        model = Blog #используемая модель
        fields = ('title', 'description', 'content', 'posted', 'author', 'image',)
        labels = {'title':"Заголовок",'description':"Краткое описание", 'content':"Содержание", 'posted':"Дата", 'author':"Автор", 'image':"Изображение",}

blog/views.py
from django.shortcuts import render, redirect
from blog.models import Blog, Comment
from blog.forms import CommentForm, BlogForm
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime

def blog(request):
    """Renders the blog page."""
    last = Blog.objects.order_by('-posted')[:3]
    assert isinstance(request, HttpRequest)
    posts = Blog.objects.all() # запрос на выбор всех статей блога из модели
    return render(
        request,
        'blog/blog.html',
        {
        'title':'Блог',
        'last': last,
        'posts': posts, # передача списка статей в шаблон веб-страницы
        'year':datetime.now().year,
        }

)

def blogpost(request, id):
    last = Blog.objects.order_by('-posted')[:3]
    post_1 = Blog.objects.get(id=id) # запрос на выбор конкретной статьи по параметру
    comments = Comment.objects.filter(post=id)
    if request.method == "POST": # после отправки данных формы на сервер методом POST
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_f = form.save(commit=False)
            comment_f.author = request.user # добавляем (так как этого поля нет в форме) в модель Комментария (Comment) в поле автор авторизованного пользователя
            comment_f.date = datetime.now() # добавляем в модель Комментария (Comment) текущую дату
            comment_f.post = Blog.objects.get(id=id) # добавляем в модель Комментария (Comment) статью, для которой данный комментарий
            comment_f.save() # сохраняем изменения после добавления полей
            return redirect('blog:blogpost', id=id) # переадресация на ту же страницу статьи после отправки комментария
    else:
        form = CommentForm() # создание формы для ввода комментария
    return render(
        request,
        'blog/blogpost.html',
        {
        	'last': last,
            'post_1': post_1, # передача конкретной статьи в шаблон веб-страницы
            'comments': comments, # передача всех комментариев к данной статье в шаблон веб-страницы
            'form': form, # передача формы добавления комментария в шаблон веб-страницы
            'year':datetime.now().year,
        }
)

def newpost(request):
    """Renders the newpost page."""
    last = Blog.objects.order_by('-posted')[:3]
    if request.method == "POST":                        #после отправки формы
        blogform = BlogForm(request.POST, request.FILES)
        if blogform.is_valid():
            blog_f = blogform.save(commit=False)
            blog_f.posted = datetime.now()
            blog_f.save()
            return redirect('blog')
    else:
        blogform = BlogForm()

    assert isinstance(request, HttpRequest)
    return render(
        request,
        'blog/newpost.html',
        {
            'blogform': blogform,
            'last': last,
            'year': datetime.now().year,
        }
    )

blog/templates/blog/blog.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}
<div class="wrapper bg-dark-white">
    <!-- HEADING-BANNER START -->
	<div class="heading-banner-area overlay-bg">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="heading-banner">
						<div class="heading-banner-title">
							<h2>Новости</h2>
						</div>
						<div class="breadcumbs pb-15">
							<ul>
								<li><a href="/">Главная</a></li>
								<li>Новости</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- HEADING-BANNER END -->
	<!-- BLGO-AREA START -->
	<div class="blog-area blog-2  pt-80 pb-80">
		<div class="container">	
			<div class="blog">
				<div class="row">
					{% for l in last %}
					<!-- Single-blog start -->
					<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
						<div class="single-blog mb-30">
							<div class="blog-photo">
								<a href="{{ l.get_absolute_url }}"><img src="{{ l.image.url }}" alt="" /></a>
							</div>
							<div class="blog-info"> 
								<div class="post-meta fix">
									<div class="post-year floatleft">
										<p class="text-uppercase text-dark-red mb-0">{{ l.date }}</p>
										<h4 class="post-title"><a href="{{ l.get_absolute_url }}" tabindex="0">{{ l.title }}</a></h4>
									</div>
								</div>
								<p>{{ l.posted }}</p>
								<a href="{{ l.get_absolute_url }}" class="button-2 text-dark-red">Читать далее...</a>
							</div>
						</div>
					</div>
					{% endfor %}
					<!-- Single-blog end -->
				</div>
				<div class="row">
					<div class="col-md-12">
						<!-- Pagination start -->
						<div class="shop-pagination  text-center">
							<div class="pagination">
								<ul>
									<li><a href="#"><i class="zmdi zmdi-long-arrow-left"></i></a></li>
									<li class="active"><a href="#">1</a></li>
									<li><a href="#"><i class="zmdi zmdi-long-arrow-right"></i></a></li>
								</ul>
							</div>
						</div>
						<!-- Pagination end -->							
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- BLGO-AREA END -->		
</div>
{% endblock %}

blog/templates/blog/blogpost.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}
<div class="wrapper bg-dark-white">
    <!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>{{ post_1.title }}</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="/">Главная</a></li>
										<li><a href="{% url 'blog:blog' %}"></a></li>
										<li>Новости</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- BLGO-AREA START -->
			<div class="blog-area blog-2 blog-details-area  pt-80 pb-80">
				<div class="container">	
					<div class="blog">
						<div class="row">
							
							<!-- Single-blog start -->
							<div class="col-lg-12">
								
								<div class="single-blog mb-30">
									
									<div class="blog-photo">
										<a href="#"><img src="{{ post_1.image.url }}" alt="" /></a>
										
									</div>
									
									<div class="blog-info blog-details-info">
										<p>{{ post_1.date }}</p>
										<h4 class="post-title post-title-2"><a href="#">{{ post_1.title }}</a></h4>
										<p>{{ post_1.content|linebreaksbr }}</p>
										<div class="pro-reviews mt-60">
											<div class="customer-review mb-60">
												<h3 class="tab-title title-border mb-30">Комментарии</h3>
												{% for comment in comments %}
												<ul class="product-comments clearfix">
													<li class="mb-30">
														<div class="pro-reviewer">
															<img src="{% static 'app/img/reviewer/1.jpg' %}" alt="" />
														</div>
														<div class="pro-reviewer-comment">
															<div class="fix">
																<div class="floatleft mbl-center">
																	<h5 class="text-uppercase mb-0"><strong>{{ comment.author }}</strong></h5>
																	<p class="reply-date">{{comment.date}}</p>
																</div>
															</div>
															<p class="mb-0">{{ comment.text|linebreaksbr }}</p>
														</div>
													</li>
												</ul>
												{% endfor %}
											</div>
											{% if user.is_authenticated %}
											<div class="leave-review">
												<h3 class="tab-title title-border mb-30">Оставьте свой отзыв</h3>
												<div class="reply-box">
													<form action="" method="POST">
														{% csrf_token %}
														<div class="row">
															<div class="col-md-12">
																<textarea class="custom-textarea"  name="text" required id="id_text" placeholder="Ваш отзыв..."></textarea>
																<button type="submit" data-text="Сохранить" class="button-one submit-button mt-20">Отправить</button>
															</div>
														</div>
													</form>
												</div>
											</div>
											 {% else %}
    										<h3 class="tab-title title-border mb-30"> Для добавления своего комментария, пожалуйста, авторизуйтесь.</h3>
											{% endif %}
										</div>										
									</div>
								</div>
							</div>
							<!-- Single-blog end -->
						</div>
					</div>
				</div>
			</div>
</div>
{% endblock %}