Raduga/urls.py
"""
Definition of urls for Raduga.
"""

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from datetime import datetime
import app.forms
import app.views
from django.shortcuts import render, redirect
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
    path('', app.views.home, name='home'),
    path('contact/', app.views.contact, name='contact'),
    path('about/', app.views.about, name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', app.views.registration, name='registration'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('product/', include('product.urls', namespace='product')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/urls.py
from django.urls import path  
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
  
app_name = 'blog'  
  
urlpatterns = [  
    path('', views.blog, name='blog'),
    path('<id>/', views.blogpost, name='blogpost'),
    path('newpost', views.newpost, name='newpost'),
]

product/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from product import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductList, name='ProductList'),
    path('<category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<slug>', views.ProductDetail, name='ProductDetail'),
]

app/templates/app/about.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}
<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>О нас</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="/">Главная</a></li>
										<li>О нас</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- ABOUT-US-AREA START -->
			<div class="about-us-area  pt-80 pb-80">
				<div class="container">	
					<div class="about-us bg-white">
						<div class="row">
							<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
								<div class="about-photo">
									<img src="{% static 'app/img/bg/about.png' %}" alt="" />
								</div>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
								<div class="about-brief bg-dark-white">
									<h4 class="title-1 title-border text-uppercase mb-30">Немного о нас</h4>
									<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magn aliqua. Ut enim ad minim veniam, ommodo consequa.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia is be deserunt mollit anim id est laborum.</p>
									<p>Sed ut perspiciatis unde omnis iste natus error sit. voluptatem accusantium doloremque laudantium, totam remes aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.</p>
									<p>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- ABOUT-US-AREA END -->
{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}
<!-- HEADING-BANNER START -->
			<div class="heading-banner-area overlay-bg">
				<div class="container">
					<div class="row">
						<div class="col-md-12">
							<div class="heading-banner">
								<div class="heading-banner-title">
									<h2>Контакты</h2>
								</div>
								<div class="breadcumbs pb-15">
									<ul>
										<li><a href="/">Главная</a></li>
										<li>Контакты</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- HEADING-BANNER END -->
			<!-- contact-us-AREA START -->
			<div class="contact-us-area  pt-80 pb-80">
				<div class="container">	
					<div class="contact-us customer-login bg-white">
						<div class="row">
							<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
								<div class="contact-details">
									<h4 class="title-1 title-border text-uppercase mb-30">контакты</h4>
									<ul>
										<li>
											<i class="zmdi zmdi-pin"></i>
											<span>ул. Ротная, д.37</span>
											<span>Псков, Россия</span>
										</li>
										<li>
											<i class="zmdi zmdi-phone"></i>
											<span>+880 1234 123456</span>
										</li>
										<li>
											<i class="zmdi zmdi-email"></i>
											<span>company-email@gmail.com</span>
										</li>
									</ul>
								</div>
								<div class="send-message mt-60">
									<form action="{% static 'app/mail.php' %}">
										<h4 class="title-1 title-border text-uppercase mb-30">Оставить сообщение</h4>
										<input type="text" name="name" placeholder="Ваше имя..." />
										<input type="text" name="email" placeholder="Ваша эл.почта..." />
										<textarea class="custom-textarea" name="message" placeholder="Ваше сообщение..."></textarea>
										<button class="button-one submit-button mt-20" data-text="Отправить" type="submit">Отправить сообщение</button>
									</form>
								</div>
							</div>
							<div class="col-lg-8 col-md-8 col-sm-7 col-xs-12 mt-xs-30">
								<div class="map-area">
									<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2125.9296813433607!2d28.344666316011125!3d57.80254298115091!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46c019269f9f9f25%3A0x6683a655557e9ed!2z0KDQvtGC0L3QsNGPINGD0LsuLCAzNywg0J_RgdC60L7Qsiwg0J_RgdC60L7QstGB0LrQsNGPINC-0LHQuy4sIDE4MDAwNA!5e0!3m2!1sru!2sru!4v1623179498521!5m2!1sru!2sru" width="100%" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- ABOUT-US-AREA END -->
{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% load staticfiles %}

{% block content %}
<!-- WRAPPER START -->
		<div class="wrapper">
<!-- SLIDER-BANNER-AREA START -->
			<section class="slider-banner-area clearfix">
				<!-- Sidebar-social-media start -->
				<div class="sidebar-social hidden-xs">
					<div class="table">
						<div class="table-cell">
							<ul>
								<li><a href="#" target="_blank" title="Google Plus"><i class="zmdi zmdi-google-plus"></i></a></li>
								<li><a href="#" target="_blank" title="Twitter"><i class="zmdi zmdi-twitter"></i></a></li>
								<li><a href="#" target="_blank" title="Facebook"><i class="zmdi zmdi-facebook"></i></a></li>
								<li><a href="#" target="_blank" title="Linkedin"><i class="zmdi zmdi-linkedin"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Sidebar-social-media end -->
				<div class="banner-left floatleft">
					<!-- Slider-banner start -->
					<div class="slider-banner">
						<div class="single-banner banner-1">
							<a class="banner-thumb" href="/product/"><img src="/static/app/img/banner/6.jpg" alt=""></a>
							
						</div>
						<div class="single-banner banner-2">
							<a class="banner-thumb" href="/blog/"><img src="/static/app/img/banner/7.jpg" alt=""></a>
						</div>
					</div>
					<!-- Slider-banner end -->
				</div>
				<div class="slider-right floatright">
					<!-- Slider-area start -->
					<div class="slider-area">
						<div class="bend niceties preview-3">
							<div id="ensign-nivoslider" class="slides">
								<img src="{% static 'app/img/slider/slider-1/11.jpg' %}" alt="" title="#slider-direction-1" />
								<img src="{% static 'app/img/slider/slider-1/22.jpg' %}" alt="" title="#slider-direction-2"  />
								<img src="{% static 'app/img/slider/slider-1/33.jpg' %}" alt="" title="#slider-direction-3"  />
							</div>
							<!-- direction 1 -->
							<div id="slider-direction-1" class="t-cn slider-direction">
								<div class="slider-progress"></div>
							</div>
							<!-- direction 2 -->
							<div id="slider-direction-2" class="slider-direction">
								<div class="slider-progress"></div>
							</div>
							<!-- direction 3 -->
							<div id="slider-direction-3" class="slider-direction">
								<div class="slider-progress"></div>
							</div>
						</div>
					</div>
					<!-- Slider-area end -->
				</div>
				<!-- Sidebar-social-media start -->
				<div class="sidebar-account hidden-xs">
					<div class="table">
						<div class="table-cell">
							<ul>
								<li><a class="search-open" href="#" title="Search"><i class="zmdi zmdi-search"></i></a></li>
								<li><a href="{% url 'login' %}" title="Login"><i class="zmdi zmdi-lock"></i></a></li>
								<li><a href="#" title="My-Account"><i class="zmdi zmdi-shopping-cart"></i></a></li>
								<li><a href="#" title="Wishlist"><i class="zmdi zmdi-favorite"></i></a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- Sidebar-social-media start -->
			</section>
			<!-- End Slider-section -->
			<!-- sidebar-search Start -->
			<div class="sidebar-search animated slideOutUp">
				<div class="table">
					<div class="table-cell">
						<div class="container">
							<div class="row">
								<div class="col-sm-8 col-sm-offset-2 p-0">
									<div class="search-form-wrap">
										<button class="close-search"><i class="zmdi zmdi-close"></i></button>
										<form action="#">
											<input type="text" placeholder="Search here..." />
											<button class="search-button" type="submit">
												<i class="zmdi zmdi-search"></i>
											</button>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- sidebar-search End -->
			<!-- CATEGORIES AREA START -->
			<div class="purchase-online-area pt-80">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="section-title text-center">
								<h2 class="title-border">Популярные товары</h2>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12 text-center">
							<!-- Nav tabs -->
							<ul class="tab-menu clearfix">
								<li>
                                    <a href="{% url 'product:ProductList' %}" data-toggle="tab"></a>
                                </li>
								
							</ul>
						</div>
						<div class="col-lg-12">
							<!-- Tab panes -->
							<div class="tab-content">
								<div class="tab-pane active">
									<div class="row">
										{% for product in products %}
										<!-- Single-product start -->
										<div class="single-product col-lg-3 col-md-4 col-sm-4 col-xs-12">
											<div class="product-img">
												<span class="pro-label new-label">new</span>
												<a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="" /></a>
											</div>
											<div class="product-info clearfix">
												<div class="fix">
													<h4 class="post-title floatleft"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h4>
													<p class="floatright hidden-sm">{{ product.category }}</p>
												</div>
											</div>
										</div>
										{% endfor %}
										<!-- Single-product end -->
									</div>
								</div>
							</div>
							
						</div>
					</div>
				</div>
			</div>
			<!-- CATEGORIES AREA END -->
			<!-- BLGO-AREA START -->
			<div class="blog-area pt-55">
				<div class="container">
					<!-- Section-title start -->
					<div class="row">
						<div class="col-lg-12">
							<div class="section-title text-center">
								<h2 class="title-border">Новости</h2>
							</div>
						</div>
					</div>
					<!-- Section-title end -->
					<div class="row">
						<!-- Single-blog start -->
						{% for l in last %}
						<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
							<div class="single-blog mt-30">
								<div class="row">
									<div class="col-lg-6 col-md-7 col-sm-7 col-xs-12">
										<div class="blog-info">
											<div class="post-meta fix">
												<div class="post-year floatleft">
													<p class="text-uppercase text-red mb-0">{{ l.date }}</p>
													<h4 class="post-title"><a href="{{ l.get_absolute_url }}" tabindex="0">{{ l.title }}</a></h4>
												</div>
											</div>
											<p>{{ l.description }}</p>
											<a href="{{ l.get_absolute_url }}" class="button-2 text-red">Читать далее...</a>
										</div>
									</div>
									<div class="col-lg-6 col-md-5 col-sm-5 col-xs-12">
										<div class="blog-photo">
											<a href="{{ l.get_absolute_url }}"><img src="{{ l.image.url }}" alt="" /></a>
										</div>
									</div>
								</div>
							</div>
						</div>
						{% endfor %}
						<!-- Single-blog end -->
					</div>
				</div>
			</div>
			<!-- BLGO-AREA END -->
			<div class="subscribe-area pt-80">
				<div class="container">
					<div class="row">
						<div class="col-lg-12">
							<div class="subscribe">
								<form action="#">
									<input type="text" placeholder="Введите свой e-mail">
									<button class="submit-button submit-btn-2 button-one" data-text="подписка" type="submit">подписка</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% load staticfiles %}
	<!-- Favicon -->
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'app/img/favicon.ico' %}" />
	<!-- Google Font -->
	<link href='https://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css' />
	<link href='https://fonts.googleapis.com/css?family=Bree+Serif' rel='stylesheet' type='text/css' />

	<!-- bootstrap v3.3.6 css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/bootstrap.min.css' %}" />
	<!-- animate css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/animate.css' %}" />
	<!-- jquery-ui.min css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/jquery-ui.min.css' %}" />
	<!-- meanmenu css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/meanmenu.min.css' %}" />
	<!-- nivo-slider css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/lib/css/nivo-slider.css' %}" />
	<!-- preview css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/lib/css/preview.css' %}" />
	<!-- slick css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/slick.css' %}" />
	<!-- lightbox css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/lightbox.min.css' %}" />
	<!-- material-design-iconic-font css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/material-design-iconic-font.css' %}" />
	<!-- All common css of theme -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/default.css' %}" />
	<!-- style css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/style.css' %}" />
    <!-- shortcode css -->
    <link rel="stylesheet" type="text/css" href="{% static 'app/css/shortcode.css' %}" />
	<!-- responsive css -->
	<link rel="stylesheet" type="text/css" href="{% static 'app/css/responsive.css' %}" />
	<!-- modernizr css -->
	<script src="{% static 'app/js/vendor/modernizr-2.8.3.min.js' %}"></script>

</head>

<body>
<!-- WRAPPER START -->
<div class="wrapper">
 <!-- Mobile-header-top Start -->
			<div class="mobile-header-top hidden-lg hidden-md hidden-sm">
				<div class="container">
					<div class="row">
						<div class="col-xs-12">
							<!-- header-search-mobile start -->
							<div class="header-search-mobile">
								<div class="table">
									<div class="table-cell">
										<ul>
											<li><a class="search-open" href="#"><i class="zmdi zmdi-search"></i></a></li>
											<li><a href="{% url 'login' %}"><i class="zmdi zmdi-lock"></i></a></li>
											<li><a href="#"><i class="zmdi zmdi-shopping-cart"></i></a></li>
											<li><a href="#"><i class="zmdi zmdi-favorite"></i></a></li>
										</ul>
									</div>
								</div>
							</div>
							<!-- header-search-mobile start -->
						</div>
					</div>
				</div>
			</div>
			<!-- Mobile-header-top End -->
			<!-- HEADER-AREA START -->
			<header id="sticky-menu" class="header">
				<div class="header-area">
					<div class="container-fluid">
						<div class="row">
							<div class="col-sm-4 col-sm-offset-4 col-xs-7">
								<div class="logo text-center">
									<a href="/"><h1><strong>Магазин</strong></h1></a>
								</div>
							</div>
							<div class="col-sm-4 col-xs-5">
								<div class="mini-cart text-right">
									<ul>
										<li>
											<a class="cart-icon" href="#">
												<i class="zmdi zmdi-account"></i>
											</a>
											<div class="mini-cart-brief text-left">
												<div class="cart-bottom  clearfix">
													{% if user.is_authenticated %}
													<a href="{% url 'logout' %}" class="button-one floatleft text-uppercase" data-text="Выйти">Выйти</a>
													{% else %}
													<a href="{% url 'login' %}" class="button-one floatleft text-uppercase" data-text="Войти">Войти</a>
													<a href="{% url 'registration' %}" class="button-one floatright text-uppercase" data-text="Регистрация">Регистрация</a>
													{% endif %}
												</div>
											</div>
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- MAIN-MENU START -->
				<div class="menu-toggle hamburger hamburger--emphatic hidden-xs">
					<div class="hamburger-box">
						<div class="hamburger-inner"></div>
					</div>
				</div>
				<div class="main-menu  hidden-xs">
					<nav>
						<ul>
							<li><a href="/">Главная</a></li>
							<li><a href="{% url 'product:ProductList' %}">Каталог</a></li>
							<li><a href="{% url 'blog:blog' %}">Новости</a></li>
							<li><a href="{% url 'contact' %}">Контакты</a>
							<li><a href="{% url 'about' %}">О нас</a>
						</ul>
					</nav>
				</div>
				<!-- MAIN-MENU END -->
			</header>
			<!-- HEADER-AREA END -->
			<!-- Mobile-menu start -->
			<div class="mobile-menu-area">
				<div class="container-fluid">
					<div class="row">
						<div class="col-xs-12 hidden-lg hidden-md hidden-sm">
							<div class="mobile-menu">
								<nav id="dropdown">
									<ul>
										<li><a href="/">Главная</a></li>
										<li><a href="{% url 'product:ProductList' %}">Каталог</a></li>
										<li><a href="{% url 'blog:blog' %}">Новости</a></li>
										<li><a href="{% url 'contact' %}">Контакты</a>
										<li><a href="{% url 'about' %}">О нас</a>
									</ul>
								</nav>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Mobile-menu end -->
{% block content %}{% endblock %}
 <footer>
<!-- Footer-area start -->
	<div class="footer-area">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
					<div class="single-footer">
						<h3 class="footer-title  title-border">Контакты</h3>
						<ul class="footer-contact">
							<li><span>Адрес :</span>ул. Ротная, д.37<br>Псков, Россия</li>
							<li><span>Телефон :</span>+123 456 78 90</li>
							<li><span>Эл. почта :</span>your-email@gmail.com</li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
					<div class="single-footer">
						<h3 class="footer-title  title-border">аккаунт</h3>
						<ul class="footer-menu">
							<li><a href="#"><i class="zmdi zmdi-dot-circle"></i>Мои заказы</a></li>
							<li><a href="#"><i class="zmdi zmdi-dot-circle"></i>Моя корзина</a></li>
							<li><a href="{% url 'login' %}"><i class="zmdi zmdi-dot-circle"></i>Войти</a></li>
							<li><a href="{% url 'logout' %}"><i class="zmdi zmdi-dot-circle"></i>Выйти</a></li>
							<li><a href="#"><i class="zmdi zmdi-dot-circle"></i>Оформить</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
					<div class="single-footer">
						<h3 class="footer-title  title-border">навигация</h3>
						<ul class="footer-menu">
							<li><a href="/"><i class="zmdi zmdi-dot-circle"></i>Главная</a></li>
							<li><a href="{% url 'product:ProductList' %}"><i class="zmdi zmdi-dot-circle"></i>Каталог</a></li>
							<li><a href="{% url 'blog:blog' %}"><i class="zmdi zmdi-dot-circle"></i>Новости</a></li>
							<li><a href="{% url 'contact' %}"><i class="zmdi zmdi-dot-circle"></i>Контакты</a></li>
							<li><a href="{% url 'about' %}"><i class="zmdi zmdi-dot-circle"></i>О нас</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Footer-area end -->
 </footer>
 <!-- FOOTER END -->
  <!-- QUICKVIEW PRODUCT -->
 <div id="quickview-wrapper">
  <!-- Modal -->
	<div class="modal fade" id="productModal" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				</div>
				<div class="modal-body">
					<div class="modal-product">
						<div class="product-images">
							<div class="main-image images">
								<img alt="#" src="{% static 'app/img/product/quickview-photo.jpg' %}"/>
							</div>
						</div>
						<!-- .product-images -->
						<div class="product-info">
							<h1>Aenean eu tristique</h1>
							<div class="price-box-3">
								<hr />
								<div class="s-price-box">
									<span class="new-price">$160.00</span>
									<span class="old-price">$190.00</span>
								</div>
								<hr />
							</div>
							<a href="shop.html" class="see-all">See all features</a>
							<div class="quick-add-to-cart">
								<form method="post" class="cart">
									<div class="numbers-row">
										<input type="number" id="french-hens" value="3">
									</div>
									<button class="single_add_to_cart_button" type="submit">Add to cart</button>
								</form>
							</div>
							<div class="quick-desc">
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam fringilla augue nec est tristique auctor. Donec non est at libero.
							</div>
							<div class="social-sharing">
								<div class="widget widget_socialsharing_widget">
									<h3 class="widget-title-modal">Share this product</h3>
									<ul class="social-icons">
										<li><a target="_blank" title="Google +" href="#" class="gplus social-icon"><i class="zmdi zmdi-google-plus"></i></a></li>
										<li><a target="_blank" title="Twitter" href="#" class="twitter social-icon"><i class="zmdi zmdi-twitter"></i></a></li>
										<li><a target="_blank" title="Facebook" href="#" class="facebook social-icon"><i class="zmdi zmdi-facebook"></i></a></li>
										<li><a target="_blank" title="LinkedIn" href="#" class="linkedin social-icon"><i class="zmdi zmdi-linkedin"></i></a></li>
									</ul>
								</div>
							</div>
						</div><!-- .product-info -->
					</div><!-- .modal-product -->
				</div><!-- .modal-body -->
			</div><!-- .modal-content -->
		</div><!-- .modal-dialog -->
	</div><!-- END Modal -->
 </div><!-- END QUICKVIEW PRODUCT -->
 </div><!-- WRAPPER END -->

	<!-- jquery latest version -->
	<script src="{% static 'app/js/vendor/jquery-1.12.0.min.js' %}"></script>
	<!-- bootstrap js -->
	<script src="{% static 'app/js/bootstrap.min.js' %}"></script>
	<!-- jquery.meanmenu js -->
	<script src="{% static 'app/js/jquery.meanmenu.js' %}"></script>
	<!-- slick.min js -->
	<script src="{% static 'app/js/slick.min.js' %}"></script>
	<!-- jquery.treeview js -->
	<script src="{% static 'app/js/jquery.treeview.js' %}"></script>
	<!-- lightbox.min js -->
	<script src="{% static 'app/js/lightbox.min.js' %}"></script>
	<!-- jquery-ui js -->
	<script src="{% static 'app/js/jquery-ui.min.js' %}"></script>
	<!-- jquery.nivo.slider js -->
	<script src="{% static 'app/lib/js/jquery.nivo.slider.js' %}"></script>

	<script src="{% static 'app/lib/home.js' %}"></script>
	<!-- jquery.nicescroll.min js -->
	<script src="{% static 'app/js/jquery.nicescroll.min.js' %}"></script>
	<!-- countdon.min js -->
	<script src="{% static 'app/js/countdon.min.js' %}"></script>
	<!-- wow js -->
	<script src="{% static 'app/js/wow.min.js' %}"></script>
	<!-- plugins js -->
	<script src="{% static 'app/js/plugins.js' %}"></script>
	<!-- main js -->
	<script src="{% static 'app/js/main.js' %}"></script>

{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Войти в аккаунт</a></li>
</ul>

{% endif %}

app/templates/app/thank-you.html
{% extends 'app/layout.html' %}
{% load staticfiles %}

{% block content %}
		<!-- WRAPPER START -->
		<div class="wrapper bg-dark-white">
			<!-- contact-us-AREA START -->
			<div class="contact-us-area  pt-80 pb-80">
				<div class="container">	
					<div class="thankyour-area bg-white mb-30">
						<div class="row">
							<div class="col-md-12">
								<div class="thankyou">
									<h2 class="text-center mb-0">Спасибо, за Ваше сообщение!</h2>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- ABOUT-US-AREA END -->
{% endblock %}
		
			
	
		